# Generated by Django 3.1.3 on 2021-01-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=30)),
                ('stand', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursec', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('Details', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('amoun', models.CharField(default='', max_length=10)),
                ('cours1', models.CharField(default='', max_length=30)),
                ('cours2', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=30)),
                ('qual', models.CharField(default=' ', max_length=30)),
                ('exp', models.CharField(default=' ', max_length=30)),
                ('mob', models.CharField(default=' ', max_length=30)),
                ('email', models.CharField(default=' ', max_length=30)),
                ('stand', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=30)),
                ('locat', models.CharField(max_length=30)),
            ],
        ),
    ]
